#!/bin/sh
#
#  Note "backwards" argument sequence
#  $1  -- output postscript file, e.g. $CX_ROOT/doc/postman/man1cx.ps
#  $2+ -- nroff man files to include in postscript, e.g., man1cx/*.1cx
#

if [ $# -lt 2 ] ; then
   echo "usage: $0 output.ps nroff*files..."
   exit 1
fi

outfile=$1
shift
troff -man -Tpost $* | /usr/lib/lp/postscript/dpost -y 0.2 - > $outfile
